\doxysection{pip.\+\_\+internal.\+exceptions.\+Command\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1_command_error}{}\label{classpip_1_1__internal_1_1exceptions_1_1_command_error}\index{pip.\_internal.exceptions.CommandError@{pip.\_internal.exceptions.CommandError}}
Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Command\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.000000cm]{classpip_1_1__internal_1_1exceptions_1_1_command_error}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when there is an error in command-line arguments\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/\+Users/kmarty/\+Documents/\+Labo3\+\_\+architecture\+\_\+killian\+\_\+marty/\+Lib/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
